### ISSUE TITLE
Show/hide data label feature

### ISSUE THREAD

**Issue by catherinesyeh** [catherinesyeh/attention-viz#10]
- [x] Have a button/option to show or hide token labels on plot, e.g.:
![image](https://user-images.githubusercontent.com/43099514/205416038-7cc21638-89a5-4156-a80e-755d8aa38934.png)
- [ ] make sure labels update when user zooms in and out (e.g., at every zoom level, show only enough so there's no overlap)
  - check out existing libraries like this [d3 option](https://observablehq.com/@stuartathompson/preventing-label-overlaps-in-d3)

Not sure if we still need a clustering option too (that just shows labels inside cluster or something?)... I'll ask martin too haha
- this is lower priority (get the show/hide feature working first)

**Comment by wowjyu** [comment]
Show text when zoom > 6. Not surprisingly there are overlappings

![Screenshot 2022-12-09 at 17 29 20](https://user-images.githubusercontent.com/14938532/206805949-c6e76668-2508-448a-8a74-5dbcacfb83fb.png)

**Comment by catherinesyeh** [comment]
New todos:
- [ ] show labels gradually as you zoom in (less at first, then more) -- **make sure there's no overlap!!**
- [ ] color code labels depending on query/key

**Comment by catherinesyeh** [comment]
- [ ] add white outline (or another layer behind main text) to help labels stand out more
