### ISSUE TITLE
Attention view for single plots

### ISSUE THREAD

**Issue by catherinesyeh** [catherinesyeh/attention-viz#7]
**Left sidebar:**
- [x] when user **clicks** on a point (right side), show attention plot for sentence on left sidebar:
  - right now, code for these plots is here: [att.html](../blob/main/att.html)
  - original bertviz repo: https://github.com/jessevig/bertviz
- [x] highlight token corresponding to point in attention plot (see below)
- [x] allow user to toggle lines off and on in attention plot to more clearly observe attn patterns
  - currently, i do this by letting people click on the token text in the attention plot
- [x] renormalize line weights after toggling 
- [x] label q + k columns
- [ ] potentially also add more complex features (e.g., input box) like in matrix view? will ask martin...

current attn view for reference:
![image](https://user-images.githubusercontent.com/43099514/205415337-33c8894c-d7eb-4f4f-94c5-c2e1a0c6e3cf.png)

**Main panel:**
- [x] will clarify with martin, but may also still want to highlight points in sentence on main plot when the user clicks on a token (see above)
  - **update:** yes we should still do this but don't make points yellow, keep query/key color schemes just outline in different color maybe? if we use highlight token method like with search, seems to be a bit slow at the moment...

**Comment by wowjyu** [comment]
The attn data is now available for drawing upon clicking a point.

Known issue: The click interaction is kinda lagging.

![Screenshot 2022-12-08 at 16 13 25](https://user-images.githubusercontent.com/14938532/206568619-6d6de844-2e0b-4ff0-90e4-470fdb8bf194.png)

**Comment by catherinesyeh** [comment]
More todos:
- [ ] fix styling
- [ ] what to do about sizing? (e.g., narrow/short screens gets cut off)

**Comment by catherinesyeh** [comment]
More todos:
- [ ] option to filter out first token
- [ ] or cls/sep

In both cases, should renormalize remaining weights afterwards

**Comment by catherinesyeh** [comment]
done for now! (letting user add new sentences = future work)
