### ISSUE TITLE
https://attentionviz.com/ fails to load because it attempts an http pull (not https)

### ISSUE THREAD

**Issue by djoldman** [catherinesyeh/attention-viz#73]
In chrome we get this error:

> xhr.js:210 Mixed Content: The page at 'https://attentionviz.com/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://18.219.70.154:8500/getMatrixData/vit-nat'. This request has been blocked; the content must be served over HTTPS.

**Comment by catherinesyeh** [comment]
Hi! Yes, sorry the system is only accessible via http (not https) right now: http://attentionviz.com/. Hopefully this fixes the error!

**Comment by djoldman** [comment]
http://attentionviz.com/ is redirected to https://attentionviz.com/

**Comment by catherinesyeh** [comment]
Hm... that's strange. I think it's working for me-- maybe try copy and pasting the url or typing it directly? Sorry for the inconvenience!
