### ISSUE TITLE
What is version of nodejs and npm needed to run this tool?

### ISSUE THREAD

**Issue by jiandan42** [catherinesyeh/attention-viz#74]
Amazing tool!
I tried several of nodejs and npm but the visualization area of the web page is always loading. 
What is the version of nodejs and npm needed to run this tool?
Thanks!

**Comment by catherinesyeh** [comment]
Thank you so much for checking out AttentionViz! 

There should be other versions of node and npm that would work to run the tool but I am currently using node version 16.18.0 and npm version 8.19.2.

**Comment by jiandan42** [comment]
Very helpful, I ran this tool successfully!
Thanks a lot.
