### ISSUE TITLE
Search feature

### ISSUE THREAD

**Issue by catherinesyeh** [catherinesyeh/attention-viz#9]
Let users search for tokens in single view & highlight results: e.g.,
![image](https://user-images.githubusercontent.com/43099514/205415668-545ea34f-0ea2-4d03-bd2e-fa72303b596a.png)

**Comment by wowjyu** [comment]
![Screenshot 2022-12-09 at 16 28 52](https://user-images.githubusercontent.com/14938532/206799011-3ac2cf9f-5ba1-4e45-a1a2-1f0b724f3a87.png)

**Comment by catherinesyeh** [comment]
maybe we should also show the # of results or indicate to the user if no results were found :)

**Comment by catherinesyeh** [comment]
More todos:
- [ ] Shrink highlighted points slightly
- [ ] Play around with opacity or make more dense areas (i.e., lots of points stacked on top of each other) brighter somehow
- [ ] Could think about having separate search mode that only searches a single plot at a time (for faster searches)
